version: '3.3'

services:
  web:
    image: alwxx/streakr-go:latest
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    environment:
      SPACES_ENVIRONMENT: production
      GIN_MODE: release

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: streakr-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: streakr-password

  redis:
    image: redis:alpine