db:
  host: db
  port: 5432
  user: postgres
  password: streakr-password
  name: streakr-db
  migrations: file://etc/streakr-go/migrations

redis:
  address: redis:6379
  password:
  db: 0

http:
  port: 3001

web:
  auth:
    minutes_timeout: 30
    hours_max_refresh: 24
